"""
Generate the server's reply table directly from the captured LCore traffic.

Every message in the capture is a self-describing record, so the table is a
transcription of bytes rather than a hand-written interpretation of them. The
previous hand-built table was the source of two separate bugs, both of the same
kind: a word transcribed in the wrong position. Generating the table removes
that entire class of error, so if a test still fails the cause is somewhere
real and visible in the logs rather than in a typo nobody can see.

The capture directory is NOT assumed to hold one session. Re-running LCore
appends a new numbered run, and if the directory is cleared part-way through a
run the surviving files start at some index other than 1. Sorting the filenames
alone silently splices those runs together into a sequence that never occurred
on the wire, which desynchronises GW2 - the exact failure this project spent
three hangs diagnosing. So the runs are separated first, and only a run that
begins at index 1 and has no gaps is allowed to become a table.

Writes replay_table.inc, included by lgpipe_server.c.

    py gen_replay.py
"""

import glob
import os
import re
import struct
import sys

PAYLOADS = r"C:\Users\Sisyphos\AppData\Local\Temp\opencode\payloads"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "replay_table.inc")

NAME_RE = re.compile(r"^read_(\d+)_(\d+)\.bin$")

# Words per entry. The longest captured reply is 32 bytes (8 words); the frame
# message never travels server->client, so 9 leaves headroom without mattering.
WORDS = 9


def collect():
    """Return every dump as (index, byte_count, mtime, words, path)."""
    out = []
    for path in sorted(glob.glob(os.path.join(PAYLOADS, "read_*.bin"))):
        base = os.path.basename(path)
        m = NAME_RE.match(base)
        if not m:
            print("  ignore %s: unrecognised name" % base)
            continue
        index, size = int(m.group(1)), int(m.group(2))
        data = open(path, "rb").read()
        if len(data) < 8 or len(data) % 4:
            print("  skip %s: %dB not word-aligned" % (base, len(data)))
            continue
        if len(data) != size:
            print("  skip %s: %dB on disk, name says %dB" % (base, len(data), size))
            continue
        words = struct.unpack("<%dI" % (len(data) // 4), data)
        length, kind = words[0], words[1]
        if length != len(data):
            print("  skip %s: length field %d != %d" % (base, length, len(data)))
            continue
        if len(words) > WORDS:
            print("  skip %s: %d words exceeds table width" % (base, len(words)))
            continue
        out.append((index, size, os.path.getmtime(path), words, base))
    return out


def split_runs(dumps):
    """
    Group dumps into capture runs.

    The proxy numbers replies from 1 within a single process lifetime, so a
    run is a maximal stretch where indices increase by one. An index that is
    not exactly one more than its predecessor means a new run began - either a
    fresh GW2/LCore launch or a truncated run whose head was deleted.
    """
    runs = []
    for d in sorted(dumps, key=lambda x: x[2]):   # wire order is write order
        if runs and d[0] == runs[-1][-1][0] + 1:
            runs[-1].append(d)
        else:
            runs.append([d])
    return runs


def pick_run(runs):
    """The first run that starts at 1 and is gap-free is the only honest choice."""
    for run in runs:
        if run[0][0] != 1:
            continue
        if [d[0] for d in run] != list(range(1, len(run) + 1)):
            print("  run %d..%d has gaps, not usable" % (run[0][0], run[-1][0]))
            continue
        return run
    return None


def tail_counter(run):
    """
    The value the 12-byte 0x0900 keepalive should carry once the table runs out.

    LCore numbers keepalives 0,1,2,3... one per message, so the tail has to
    continue from the last one captured or the client sees the counter go
    backwards. Computed rather than hardcoded so that a longer, cleaner capture
    automatically produces a correct starting point.
    """
    for d in reversed(run):
        w = d[3]
        if len(w) == 3 and w[1] == 0x0900:
            return (w[2] + 1) & 0xFFFFFFFF
    return 2   # capture shows the 12-byte keepalive first appearing at 2


def emit(run):
    lines = [
        "/*",
        " * GENERATED by gen_replay.py - do not edit by hand.",
        " *",
        " * Verbatim replies captured from LCore.exe, in wire order. Each entry is",
        " * one message as a flat word array, ready to WriteFile.",
        " */",
        "",
        "#define REPLAY_COUNT %d" % len(run),
        "",
        "/* Counter for the keepalive sent after the table is exhausted. */",
        "#define REPLAY_TAIL_COUNTER %uu" % tail_counter(run),
        "",
        "static const DWORD g_replay[REPLAY_COUNT][%d] = {" % WORDS,
    ]
    for d in run:
        cells = ", ".join("0x%08xu" % w for w in d[3])
        lines.append("    { %s%s }," % (cells, ", 0" * (WORDS - len(d[3]))))
    lines.append("};")
    lines.append("")
    lines.append("/* Message lengths, parallel to the table above, one per line. */")
    lines.append("static const DWORD g_replay_len[REPLAY_COUNT] = {")
    for d in run:
        # Parenthesised deliberately: "%" and "*" bind equally tightly, so
        # `"%d" % n * 4` would format once and repeat the string four times.
        lines.append("    %d," % (len(d[3]) * 4))
    lines.append("};")
    lines.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")


def main():
    dumps = collect()
    if not dumps:
        raise SystemExit("no usable captures found in " + PAYLOADS)

    runs = split_runs(dumps)
    print("found %d dumps in %d run(s):" % (len(dumps), len(runs)))
    for n, run in enumerate(runs, 1):
        kinds = {}
        for d in run:
            kinds[d[3][1]] = kinds.get(d[3][1], 0) + 1
        summary = "  ".join("0x%04x x%d" % (k, v) for k, v in sorted(kinds.items()))
        print("  run %d: replies %d..%d (%d msgs)  %s"
              % (n, run[0][0], run[-1][0], len(run), summary))

    run = pick_run(runs)
    if run is None:
        raise SystemExit(
            "\nNo run starts at reply 1 with no gaps, so no table can be trusted.\n"
            "Re-capture: clear the payloads directory, then start LCore and GW2\n"
            "fresh and let the session run to completion without clearing it.")

    emit(run)
    print("\nwrote %s" % OUT)
    print("  %d replies, indices 1..%d" % (len(run), len(run)))
    print("  tail keepalive resumes at counter %d" % tail_counter(run))
    if len(runs) > 1:
        print("\nNOTE: %d other run(s) were ignored. They are not part of this" % (len(runs) - 1))
        print("      table; splicing them in is what desynchronises the client.")


if __name__ == "__main__":
    main()
